### ISSUE TITLE
LINQ Expression Tree from JMESPath query

### ISSUE THREAD

**Issue by mcintyre321** [jdevillard/JmesPath.Net#21]
I'm not asking for it to be done, but as you have in depth knowledge of JMESPath, is it conceivably possible for JMESPath queries to be mapped into LINQ Expression Trees*? 

*There may be some operations that aren't coverted in System.Linq which could have custom Methods in a well-known namespace, I think that would be allowed under the scope of my question!

**Comment by jdevillard** [comment]
Hello, 

Thanks for your interest in the Jmespath.Net.

Could you please give us some examples of your use case? (JMESPATH <-> Linq) so we can discuss about it !

Thanks

**Comment by mcintyre321** [comment]
So I have this idea about putting JMESPath queries into HTTP range headers,
to allow clients to filter and transform JSON responses.

A basic version could be done with a simple response filter, which
intercepts the JSON returned from a controller action and runs the query on
it.

If the query could be turned into a LINQ expression, it would be possible
to pass that to the data store, for allowing efficient querying of very
large resources. Kinda like Linq-to-Odata.

If LINQ compatibility isn't possible, it would be neat to be able to
inspect the JMESQuery as an AST, then the controller could pick some
filters from it to apply at the data query level.

**Comment by springcomp** [comment]
This is currently outside the scope of what resources we can invest in.
We welcome contributions though, so please feel free to contribute.

**Comment by mcintyre321** [comment]
Is there an easy way to get hold of the internal AST / parser output?

**Comment by springcomp** [comment]
@mcintyre321 Hum... no there is not.

There is some support for walking the AST from the internal implementation perspective.
For instance, if you were to write the program:

```
    internal class Program
    {
        internal sealed class MyVisitor : IVisitor
        {
            public void Visit(JmesPathExpression expression)
            {
                Console.WriteLine(expression.GetType().Name);
            }
        }
        static void Main(string[] args)
        {
            var jp = new DevLab.JmesPath.JmesPath();
            var exp = jp.Parse("foo.bar");
            exp.Accept(new MyVisitor());
        }
    }
```

You would be closest to what you need but this is currently not useful because:

- The `Expression` object does not implement the `Accept()` method so does not actually walk the AST.
- Most `JmesPathExpression` derived-types do not expose their internal structures.

Can you please elaborate why you need this and what are the use cases.
I would love to help you and improve `JMESPath.Net` to support your scenarios.
